build:
  image: yveshoppe/joomla-systemtests:latest
  commands:
    - chmod a+x .drone/build.sh
    - ./.drone/build.sh
    - apache2ctl start
    - service mysql start
    - cd /tests/www
    - export DISPLAY=:0
    - Xvfb -screen 0 1024x768x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
    - sleep 3
    - fluxbox &
    - vendor/bin/robo run:tests
  clone:
    depth: 1
    path: repo
