name: Setup Cypress
description: Install Cypress and browser dependencies

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}

    - run: npx cypress install
      shell: bash
