name: Setup Cypress
description: Fix Cypress permissions and verify binary

runs:
  using: composite
  steps:
    - name: Fix Cypress binary permissions
      shell: bash
      run: |
        if [ -f /usr/local/bin/cypress ]; then
          chmod +x /usr/local/bin/cypress
        fi

        if [ -d "$HOME/.cache/Cypress" ]; then
          chmod -R +x "$HOME/.cache/Cypress"
        fi

    - name: Verify Cypress
      shell: bash
      run: |
        /usr/local/bin/cypress verify
