name: Setup Cypress
description: Ensure Cypress is executable in container

runs:
  using: composite
  steps:
    - name: Fix Cypress permissions
      shell: bash
      run: |
        if [ -d "$HOME/.cache/Cypress" ]; then
          chmod -R +x "$HOME/.cache/Cypress"
        fi

    - name: Verify Cypress
      shell: bash
      run: |
        npx cypress verify
