<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_weblinks
 *
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\String\PunycodeHelper;

$weblinkUrl = PunycodeHelper::urlToUTF8($this->item->url);
?>
<div class="item-page">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? Factory::getApplication()->get('language') : $this->item->language; ?>" />
	<div class="page-header">
		<h2 itemprop="headline">
			<?php echo $this->escape($this->item->title); ?>
		</h2>
	</div>
	<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
	<?php echo $this->item->event->afterDisplayTitle; ?>
	<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
	<?php echo $this->item->event->beforeDisplayContent; ?>
	<div itemprop="articleBody">
		<a href="<?php echo $weblinkUrl; ?>" target="_blank" itemprop="url">
			<?php echo $weblinkUrl; ?>
		</a>
		
		<?php if (($this->params->get('show_link_description')) && ($this->item->description != '')) : ?>
			<div class="mt-2 mb-2">
				<?php $images = json_decode($this->item->images); ?>
				<?php  if (!empty($images->image_first)) : ?>
					<?php $imgFloat = '';
					if (!empty($images->float_first)) :
						$imgFloat = $images->float_first == 'right' ? 'float-end' : 'float-start';
					endif;
					$img      = HTMLHelper::cleanImageURL($images->image_first);
					$alt      = empty($images->image_first_alt) && empty($images->image_first_alt_empty)
						? ''
						: 'alt="' . htmlspecialchars($images->image_first_alt, ENT_COMPAT, 'UTF-8') . '"';
					?>
					<figure class="item-image <?php echo $imgFloat; ?>">
						<img src="<?php echo htmlspecialchars($img->url, ENT_COMPAT, 'UTF-8'); ?>"
								<?php echo $alt; ?> itemprop="thumbnail" />
						<?php if (!empty($images->image_first_caption)) : ?>
							<figcaption class="caption"><?php echo htmlspecialchars($images->image_first_caption, ENT_COMPAT, 'UTF-8'); ?></figcaption>
						<?php endif; ?>
					</figure>
				<?php endif; ?>

				<?php  if (!empty($images->image_second)) : ?>
					<?php $imgFloat = '';
					if (!empty($images->float_second)) :
						$imgFloat = $images->float_second == 'right' ? 'float-end' : 'float-start';
					endif;
					$img      = HTMLHelper::cleanImageURL($images->image_second);
					$alt      = empty($images->image_first_alt) && empty($images->image_second_alt_empty)
						? ''
						: 'alt="' . htmlspecialchars($images->image_second_alt, ENT_COMPAT, 'UTF-8') . '"';
					?>
					<figure class="item-image <?php echo $imgFloat; ?>">
						<img src="<?php echo htmlspecialchars($img->url, ENT_COMPAT, 'UTF-8'); ?>"
								<?php echo $alt; ?> itemprop="thumbnail" />
						<?php if (!empty($images->image_second_caption)) : ?>
							<figcaption class="caption"><?php echo htmlspecialchars($images->image_second_caption, ENT_COMPAT, 'UTF-8'); ?></figcaption>
						<?php endif; ?>
					</figure>
				<?php endif; ?>

				<?php echo $this->item->description; ?>

			</div>
		<?php endif; ?>
	</div>
	<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
	<?php echo $this->item->event->afterDisplayContent; ?>
</div>
