name: Crowdin Action
# Controls when the action will run.
on:
  schedule:
    - cron: '30 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  synchronize-with-crowdin:
    if: (github.event_name == 'schedule' && github.repository == 'joomla-extensions/weblinks') || (github.event_name != 'schedule')
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Runs the Crowdin action command - https://github.com/crowdin/github-action
      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          # Upload sources to Crowdin
          upload_sources: true
          # Upload translations to Crowdin, only use true at initial run
          upload_translations: false
          # Make pull request of Crowdin translations
          download_translations: true
          # Only download translated strings
          skip_untranslated_strings: false
          # Download translations with pushing to branch
          push_translations: true
          # To download translations to the specified version branch
          localization_branch_name: 'l10n_crowdin_translations'
          # Create pull request after pushing to branch
          create_pull_request: true
          # Configuration file to use
          config: 'crowdin.yml'
          # Use true for dryrun to test the run without actually processing anything
          dryrun_action: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
